/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from "react";
import { Link, Navigate } from "react-router-dom";
import { CheckCircle2, Clock3, ImagePlus, LogOut, MessageCircle, Plane, Save, Trash2, Upload } from "lucide-react";
import { useStore } from "../lib/store";
import { getPaymentMethod } from "../lib/data";
import { supabase } from "../lib/supabase";
import type { Destination, Flight, MediaItem } from "../lib/types";
import { money } from "../lib/utils";

const emptyPackage: Destination = { id: 0, name: "", location: "", description: "", price: 0, rating: "5.0", reviews: "", image: "" };
const emptyFlight: Flight = { id: 0, airline: "", departure_city: "", arrival_city: "", departure_date: "", arrival_date: "", price: 0, available_seats: 0, duration: "", stops: "Non-stop" };

export function NewAdminDashboard() {
  const { user, isAdmin, bookings, destinations, flights, media, saveDestination, deleteDestination, saveFlight, deleteFlight, deleteMedia, approveBooking, rejectBooking, updateBookingPayment, signOut, notify } = useStore();
  const [tab, setTab] = useState<"bookings" | "packages" | "flights" | "media">("bookings");
  const [selected, setSelected] = useState<string | null>(null);
  const [pkg, setPkg] = useState(emptyPackage);
  const [packageFiles, setPackageFiles] = useState<File[]>([]);
  const [flight, setFlight] = useState(emptyFlight);
  const [payment, setPayment] = useState({ instructions: "", amount: "", reference: "", status: "pending" as "unpaid" | "pending" | "paid" | "failed" });
  const pending = bookings.filter((b) => b.status === "pending");
  const current = bookings.find((b) => b.id === selected);
  const maxMedia = 5;

  if (!user || !isAdmin) return <Navigate to="/" replace />;
  const selectBooking = (id: string) => { const b = bookings.find((x) => x.id === id); setSelected(id); setPayment({ instructions: b?.paymentInstructions ?? "", amount: b?.paymentAmount?.toString() ?? "", reference: b?.paymentReference ?? "", status: b?.paymentStatus ?? "pending" }); };
  const savePayment = async () => { if (!current) return; const amount = Number(payment.amount); if (!Number.isFinite(amount) || amount < 0) return notify("Enter a valid payment amount", "error"); await updateBookingPayment(current.id, { ...payment, amount }); };
  const uploadMedia = async (files: FileList | null) => {
    if (!files || !supabase) return;
    const selectedFiles = Array.from(files);
    if (selectedFiles.length < 1 || selectedFiles.length > maxMedia) return notify("Select between 1 and 5 files", "error");
    const adminMediaCount = media.filter((item) => item.source !== "seed").length;
    if (adminMediaCount + selectedFiles.length > maxMedia) return notify("The homepage gallery can contain a maximum of 5 admin uploads", "error");
    for (const file of selectedFiles) {
      if (!(file.type.startsWith("image/") || file.type.startsWith("video/")) || file.size > 50 * 1024 * 1024) { notify("Use images or videos under 50 MB", "error"); return; }
    }
    for (const file of selectedFiles) {
      const id = crypto.randomUUID(); const path = `${id}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`;
      const upload = await supabase.storage.from("media").upload(path, file, { contentType: file.type });
      if (upload.error) { notify("Media upload failed", "error"); return; }
      const { data } = supabase.storage.from("media").getPublicUrl(path);
      const row = { id, file_url: data.publicUrl, file_type: file.type.startsWith("video/") ? "video" : "photo", file_name: file.name, bucket: "media", title: file.name };
      const result = await supabase.from("media").insert(row);
      if (result.error) { await supabase.storage.from("media").remove([path]); notify("Could not publish media", "error"); return; }
    }
    notify(`${selectedFiles.length} media item${selectedFiles.length === 1 ? "" : "s"} published`);
    window.location.reload();
  };
  const uploadPackageMedia = async () => {
    if (!supabase || packageFiles.length < 1 || packageFiles.length > 5) return notify("Select between 1 and 5 images or videos", "error");
    for (const file of packageFiles) if (!(file.type.startsWith("image/") || file.type.startsWith("video/")) || file.size > 50 * 1024 * 1024) return notify("Use images or videos under 50 MB", "error");
    const assets: MediaItem[] = [];
    for (const file of packageFiles) { const id = crypto.randomUUID(); const path = `packages/${pkg.id || Date.now()}/${id}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const upload = await supabase.storage.from("media").upload(path, file, { contentType: file.type }); if (upload.error) return notify("Package media upload failed", "error"); const { data } = supabase.storage.from("media").getPublicUrl(path); assets.push({ id, url: data.publicUrl, type: file.type.startsWith("video/") ? "video" : "photo", title: file.name, source: "media" }); }
    const saved = await saveDestination({ ...pkg, id: pkg.id || 0, image: assets[0]?.url || pkg.image, media: assets });
    if (saved) { setPackageFiles([]); setPkg(emptyPackage); notify("Luxury package published with media"); }
  };
  const nav = (next: typeof tab) => setTab(next);
  return <div className="min-h-screen bg-primary text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-accent">ATL Travels</p><h1 className="font-display mt-1 text-2xl font-bold">Operations desk</h1></div><div className="flex items-center gap-2"><Link to="/chat" className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold"><MessageCircle className="mr-2 inline h-4 w-4" />Chat</Link><Link to="/" className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">View site</Link><button onClick={signOut} className="rounded-full bg-accent px-4 py-2 text-sm font-bold"><LogOut className="mr-2 inline h-4 w-4" />Sign out</button></div></div></header><main className="mx-auto max-w-7xl px-5 py-8"><div className="grid gap-4 sm:grid-cols-3"><Stat label="Needs review" value={pending.length} icon={Clock3} /><Stat label="Published packages" value={destinations.length} icon={CheckCircle2} /><Stat label="Published flights" value={flights.length} icon={Plane} /></div><nav className="mt-8 flex flex-wrap gap-2">{([["bookings","Bookings"],["packages","Luxury Packages"],["flights","Flight posts"],["media","Media gallery"]] as const).map(([key,label]) => <button key={key} onClick={() => nav(key)} className={`rounded-full px-4 py-2 text-sm font-bold ${tab === key ? "bg-accent text-primary" : "bg-white/10 text-white"}`}>{label}</button>)}</nav>{tab === "bookings" && <BookingPanel bookings={bookings} current={current} selected={selected} selectBooking={selectBooking} payment={payment} setPayment={setPayment} savePayment={savePayment} approveBooking={approveBooking} rejectBooking={rejectBooking} />}{tab === "packages" && <CatalogPanel title="Luxury Packages" items={destinations} draft={pkg} setDraft={setPkg} onSave={uploadPackageMedia} onDelete={deleteDestination} kind="package" packageFiles={packageFiles} setPackageFiles={setPackageFiles} />}{tab === "flights" && <CatalogPanel title="Flight posts" items={flights} draft={flight} setDraft={setFlight} onSave={async () => { const saved = await saveFlight({ ...flight, id: flight.id || 0 }); if (saved) setFlight(emptyFlight); }} onDelete={deleteFlight} kind="flight" />}{tab === "media" && <MediaPanel media={media} uploadMedia={uploadMedia} deleteMedia={deleteMedia} max={maxMedia} />}</main></div>;
}

function BookingPanel({ bookings, current, selected, selectBooking, payment, setPayment, savePayment, approveBooking, rejectBooking }: any) { return <section className="mt-8 grid gap-5 lg:grid-cols-[1fr_420px]"><div className="space-y-3">{bookings.map((b: any) => <button key={b.id} onClick={() => selectBooking(b.id)} className={`w-full rounded-2xl border p-5 text-left ${selected === b.id ? "border-accent bg-white/10" : "border-white/10 bg-white/5"}`}><div className="flex justify-between"><span className="font-bold">{b.itemName}</span><span className="text-accent">{b.status}</span></div><p className="mt-2 text-sm text-white/60">{b.bookedBy} · {b.userEmail} · {money(b.total)}</p></button>)}</div>{current ? <aside className="rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="font-display text-2xl font-bold">Booking details</h2><div className="mt-4 space-y-2 text-sm"><Detail label="Traveler" value={current.traveler.fullName} /><Detail label="Phone" value={current.traveler.phone} /><Detail label="Passport" value={current.traveler.passport} /><Detail label="Payment method" value={getPaymentMethod(current.paymentMethod).name} /><Detail label="Total" value={money(current.total)} /></div><textarea value={payment.instructions} onChange={(e) => setPayment({ ...payment, instructions: e.target.value })} placeholder="Payment instructions" className="mt-5 min-h-20 w-full rounded-xl bg-white/10 p-3" /><div className="mt-3 grid grid-cols-2 gap-2"><input value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: e.target.value })} placeholder="Amount" type="number" className="rounded-xl bg-white/10 p-3" /><input value={payment.reference} onChange={(e) => setPayment({ ...payment, reference: e.target.value })} placeholder="Reference" className="rounded-xl bg-white/10 p-3" /></div><select value={payment.status} onChange={(e) => setPayment({ ...payment, status: e.target.value })} className="mt-3 w-full rounded-xl bg-white/10 p-3"><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="unpaid">Unpaid</option></select><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => approveBooking(current.id, payment.instructions)} className="rounded-full bg-emerald-500 px-4 py-2 font-bold">Approve</button><button onClick={savePayment} className="rounded-full bg-accent px-4 py-2 font-bold text-primary"><Save className="mr-1 inline h-4 w-4" />Save payment</button><button onClick={() => rejectBooking(current.id)} className="rounded-full bg-red-500/20 px-4 py-2 font-bold text-red-200">Reject</button></div></aside> : <Empty text="Select a booking to review" />}</section>; }

function CatalogPanel({ title, items, draft, setDraft, onSave, onDelete, kind, packageFiles, setPackageFiles }: any) { const isPackage = kind === "package"; return <section className="mt-8 grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={(e) => { e.preventDefault(); onSave(); }} className="rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="font-display text-2xl font-bold">{draft.id ? "Edit" : "Create"} {title}</h2>{(isPackage ? [["name","Name"],["location","Location"],["description","Description"],["price","Price"]] : [["airline","Airline"],["departure_city","From"],["arrival_city","To"],["departure_date","Departure"],["arrival_date","Arrival"],["price","Price"],["available_seats","Seats"],["duration","Duration"],["stops","Stops"]]).map(([key,label]) => <label key={key} className="mt-3 block text-sm font-bold"><span className="mb-1 block text-white/60">{label}</span><input type={key.includes("date") ? "datetime-local" : key === "price" || key === "available_seats" ? "number" : "text"} value={draft[key]} onChange={(e) => setDraft({ ...draft, [key]: key === "price" || key === "available_seats" ? Number(e.target.value) : e.target.value })} required className="w-full rounded-xl bg-white/10 p-3" /></label>)}{isPackage && <label className="mt-4 block rounded-xl border border-dashed border-accent/60 p-4 text-sm font-bold"><span className="mb-2 block text-white/60">Package images or videos (1–5)</span><input type="file" accept="image/*,video/*" multiple onChange={(e) => setPackageFiles?.(Array.from(e.target.files ?? []))} className="w-full text-sm" />{packageFiles?.length ? <span className="mt-2 block text-accent">{packageFiles.length} selected</span> : null}</label>}<button className="mt-5 w-full rounded-full bg-accent px-4 py-3 font-bold text-primary"><Save className="mr-2 inline h-4 w-4" />Publish</button></form><div className="space-y-3">{items.map((item: any) => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4"><div><p className="font-bold">{isPackage ? item.name : `${item.airline} · ${item.departure_city} → ${item.arrival_city}`}</p><p className="text-sm text-white/55">{isPackage ? item.location : money(item.price)}</p></div><div className="flex gap-2"><button onClick={() => setDraft(item)} className="rounded-full bg-white/10 px-3 py-2 text-sm font-bold">Edit</button><button onClick={() => onDelete(item.id)} className="rounded-full bg-red-500/20 p-2 text-red-200" aria-label="Delete"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></section>; }

function MediaPanel({ media, uploadMedia, deleteMedia, max }: { media: MediaItem[]; uploadMedia: (files: FileList | null) => void; deleteMedia: (id: string) => void; max: number }) { return <section className="mt-8"><div className="rounded-2xl border border-dashed border-accent/60 bg-white/5 p-8 text-center"><Upload className="mx-auto h-8 w-8 text-accent" /><h2 className="font-display mt-3 text-2xl font-bold">Homepage media gallery</h2><p className="mt-2 text-sm text-white/60">Upload 1–5 images or videos. {media.filter((item) => item.source !== "seed").length}/{max} admin items published.</p><label className="mt-5 inline-flex cursor-pointer rounded-full bg-accent px-5 py-3 font-bold text-primary"><ImagePlus className="mr-2 h-5 w-5" />Choose media<input type="file" accept="image/*,video/*" multiple hidden onChange={(e) => uploadMedia(e.target.files)} /></label></div><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-5">{media.map((item) => <div key={item.id} className="relative overflow-hidden rounded-2xl bg-white/10"><img src={item.url} alt={item.title} className="aspect-square w-full object-cover" />{item.type === "video" && <span className="absolute left-2 top-2 rounded bg-primary px-2 py-1 text-xs">Video</span>}<button onClick={() => deleteMedia(item.id)} className="absolute right-2 top-2 rounded-full bg-red-500 p-2" aria-label="Delete media"><Trash2 className="h-4 w-4" /></button></div>)}</div></section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-white/10 pb-2"><span className="text-white/50">{label}</span><span className="text-right font-bold">{value || "—"}</span></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-12 text-center text-white/50">{text}</div>; }
function Stat({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Plane }) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><Icon className="h-5 w-5 text-accent" /><p className="font-display mt-3 text-3xl font-bold">{value}</p><p className="text-sm text-white/55">{label}</p></div>; }
